In [ ]:
'LUV TSLA'

In [2]:
# import required libraries
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import datetime as dt
from sklearn import preprocessing

In [9]:
data = yf.download('LUV TSLA', start = '2020-01-01',end = dt.date.today())

[*********************100%***********************]  2 of 2 completed

In [10]:
data

            Adj Close                  Close                   High  \
                  LUV        TSLA        LUV        TSLA        LUV
Date
2019-12-31  53.773045   83.666000  53.980000   83.666000  54.119999
2020-01-02  54.629749   86.052002  54.840000   86.052002  54.869999
2020-01-03  54.141628   88.601997  54.349998   88.601997  54.419998
2020-01-06  53.922474   90.307999  54.130001   90.307999  54.560001
2020-01-07  54.081860   93.811996  54.290001   93.811996  54.400002
...               ...         ...        ...         ...        ...
2021-02-08  52.240002  863.419983  52.240002  863.419983  53.290001
2021-02-09  51.180000  849.460022  51.180000  849.460022  51.750000
2021-02-10  51.279999  804.820007  51.279999  804.820007  52.340000
2021-02-11  51.419998  811.659973  51.419998  811.659973  51.480000
2021-02-12  51.340000  816.119995  51.340000  816.119995  51.840000

                              Low                   Open              \
                  TSLA        LUV        TSLA        LUV        TSLA
Date
2019-12-31   84.258003  53.820000   80.416000  54.040001   81.000000
2020-01-02   86.139999  54.290001   84.342003  54.380001   84.900002
2020-01-03   90.800003  53.040001   87.384003  53.599998   88.099998
2020-01-06   90.311996  53.480000   88.000000  53.689999   88.094002
2020-01-07   94.325996  53.880001   90.671997  54.330002   92.279999
...                ...        ...         ...        ...         ...
2021-02-08  877.770020  50.209999  854.750000  50.520000  869.669983
2021-02-09  859.799988  50.529999  841.750000  51.529999  855.119995
2021-02-10  844.820007  51.160000  800.020020  51.500000  843.640015
2021-02-11  829.880005  50.340000  801.729980  51.020000  812.440002
2021-02-12  817.330017  50.970001  785.330017  51.299999  801.260010

              Volume
                 LUV      TSLA
Date
2019-12-31   2881100  51428500
2020-01-02   3713000  47660500
2020-01-03   3536100  88892500
2020-01-06   4200300  50665000
2020-01-07   2997600  89410500
...              ...       ...
2021-02-08  11359100  20161700
2021-02-09   5409800  15157700
2021-02-10   7570800  36216100
2021-02-11   5238000  21580700
2021-02-12   4658500  23701700

[283 rows x 12 columns]

In [12]:
data_arry= data.values
data_arry

array([[5.37730446e+01, 8.36660004e+01, 5.39799995e+01, ...,
        8.10000000e+01, 2.88110000e+06, 5.14285000e+07],
       [5.46297493e+01, 8.60520020e+01, 5.48400002e+01, ...,
        8.49000015e+01, 3.71300000e+06, 4.76605000e+07],
       [5.41416283e+01, 8.86019974e+01, 5.43499985e+01, ...,
        8.80999985e+01, 3.53610000e+06, 8.88925000e+07],
       ...,
       [5.12799988e+01, 8.04820007e+02, 5.12799988e+01, ...,
        8.43640015e+02, 7.57080000e+06, 3.62161000e+07],
       [5.14199982e+01, 8.11659973e+02, 5.14199982e+01, ...,
        8.12440002e+02, 5.23800000e+06, 2.15807000e+07],
       [5.13400002e+01, 8.16119995e+02, 5.13400002e+01, ...,
        8.01260010e+02, 4.65850000e+06, 2.37017000e+07]])

In [21]:
#Normalize data with MinMaxScaler using SK-Learn
min_max_scaled = preprocessing.MinMaxScaler()
scaled_data= min_max_scaled.fit_transform(data_arry)
df_scaled_data = pd.DataFrame(scaled_data)
df_scaled_data.columns = data.columns
df_scaled_data.index = data.index
df_scaled_data.head()

           Adj Close               Close                High            \
                 LUV      TSLA       LUV      TSLA       LUV      TSLA
Date
2019-12-31  0.868125  0.014087  0.868474  0.014087  0.861552  0.004010
2020-01-02  0.892996  0.017029  0.893279  0.017029  0.883598  0.006307
2020-01-03  0.878825  0.020174  0.879146  0.020174  0.870370  0.011994
2020-01-06  0.872463  0.022278  0.872801  0.022278  0.874486  0.011398
2020-01-07  0.877090  0.026599  0.877416  0.026599  0.869782  0.016297

                 Low                Open              Volume
                 LUV      TSLA       LUV      TSLA       LUV      TSLA
Date
2019-12-31  0.882353  0.012868  0.868555  0.007422  0.007545  0.125272
2020-01-02  0.895581  0.017767  0.878187  0.012199  0.015959  0.112258
2020-01-03  0.860400  0.021562  0.856091  0.016119  0.014170  0.254665
2020-01-06  0.872784  0.022331  0.858640  0.016111  0.020887  0.122635
2020-01-07  0.884042  0.025664  0.876771  0.021239  0.008723  0.256454

In [23]:
#Normalize data with (data-data.mean())/data.std()
normalized_data = (data - data.mean())/data.std()
normalized_data.head()

           Adj Close               Close                High            \
                 LUV      TSLA       LUV      TSLA       LUV      TSLA
Date
2019-12-31  1.541452 -1.133367  1.552715 -1.133367  1.484881 -1.148174
2020-01-02  1.643233 -1.123016  1.654258 -1.123016  1.574698 -1.140134
2020-01-03  1.585242 -1.111954  1.596402 -1.111954  1.520808 -1.120227
2020-01-06  1.559205 -1.104553  1.570426 -1.104553  1.537574 -1.122312
2020-01-07  1.578141 -1.089353  1.589318 -1.089353  1.518413 -1.105164

                 Low                Open              Volume
                 LUV      TSLA       LUV      TSLA       LUV      TSLA
Date
2019-12-31  1.616541 -1.130533  1.560167 -1.145194 -0.932167 -0.478709
2020-01-02  1.671553 -1.113086  1.600590 -1.128213 -0.853926 -0.571859
2020-01-03  1.525244 -1.099568  1.507853 -1.114281 -0.870564  0.447454
2020-01-06  1.576745 -1.096830  1.518554 -1.114307 -0.808096 -0.497584
2020-01-07  1.623564 -1.084957  1.594646 -1.096082 -0.921210  0.460259